baseURL = 'https://restuhaqza.dev/'
languageCode = 'en-us'
title = 'Restu Muzakir'
theme = 'hello-friend-ng'
paginate = 10

summary = 'Restuhaqza is a software engineer from Indonesian who is passionate about DevOps things and Open Source Enthusiast.'

[markup.goldmark.renderer]
  unsafe = true

[author]
  name = 'Restu Muzakir'
  email = 'hi@restuhaqza.dev'

[params]
  description = 'Restuhaqza is a software engineer from Indonesian who is passionate about DevOps things and Open Source Enthusiast.'
  [params.logo]
    logoText = '$ echo "Hello World"'


  [params.portrait]
    path = 'img/portrait.jpeg'
    alt = 'Restu Muzakir'
  
  [[params.social]]
    name = 'github'
    url = 'https://github.com/restuhaqza'

  [[params.social]]
    name = 'linkedin'
    url = 'https://www.linkedin.com/in/restuhaqza/'

  [[params.social]]
    name = 'twitter'
    url = 'https://twitter.com/restuhaqza'

  [[params.social]]
    name = 'instagram'
    url = 'https://www.instagram.com/restuhaqza/'

  [[params.social]]
    name = 'email'
    url = 'mailto:hi@restuhaqza.dev'

[params.footer]
  trademark = '2024 All rights reserved'
  author = true
  top_text = ['Back to top']
  
[menus]
  [[menus.main]]
    identifier = 'blog'
    url = '/blog/'
    name = 'Blog'

  [[menus.main]]
    identifier = 'about'
    url = '/about/'
    name = 'About'

  [[menus.main]]
    identifier = 'newsletter'
    url = '/newsletter/'
    name = 'Newsletter'








